# Generated by Django 3.2.8 on 2021-10-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=70)),
                ('confirm_password', models.CharField(max_length=70)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gram.comments')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gram.picture')),
            ],
        ),
    ]
