# Generated by Django 3.2.8 on 2021-10-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_alter_picture_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile/')),
            ],
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='likes',
        ),
    ]
