# Generated by Django 3.2.8 on 2021-10-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0007_picture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gram.comments'),
        ),
    ]
