# Generated by Django 3.2.8 on 2021-10-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0009_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gram.picture'),
        ),
    ]
